### ISSUE TITLE
Error not sending results

### ISSUE THREAD

**Issue by jedai47** [hmaverickadams/Windows-WiFi-Extractor#1]
Hi I got the following error and didnt receive anything on my website despite the xmls being created in the directory:

C:\Users\walid\Music> python .\steal.py
Traceback (most recent call last):
  File "C:\Users\walid\Music\steal.py", line 28, in <module>
    password = root[4][0][1][2].text
IndexError: child index out of range

**Comment by hmaverickadams** [comment]
Issue should be resolved now that hardcoded XML paths have been removed.
