### ISSUE TITLE
I get a problem when starting the tool

### ISSUE THREAD

**Issue by tiag0-infosec** [hmaverickadams/Windows-WiFi-Extractor#5]
Running with python:

 line 13, in <module>
    get_profiles_command = subprocess.run(["netsh", "wlan", "show", "profiles"], stdout=subprocess.PIPE).stdout.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 45: invalid start byte
![stealer](https://user-images.githubusercontent.com/63066639/184235401-cfbc02c1-66f3-49c5-986f-0f4dcd9db374.png)

running with python3:
![stealer1](https://user-images.githubusercontent.com/63066639/184235586-1ea4b266-7575-4faa-8619-e1b7695e4dd8.png)

**Comment by hmaverickadams** [comment]
Hello,

The script needs to be run in Python3.  As your error suggests, you do not have requests installed.  You will need to install the requirements, per the instructions on the home page.

**Comment by tiag0-infosec** [comment]
Hello, 

 Everything was installed the requirements.txt file.
![requi](https://user-images.githubusercontent.com/63066639/184401455-0fd2746c-f11d-49b7-9822-e8db545ef7d6.png)

 I also ran the tool with python3, it didn't work either. There in my last image is the output after executing with python3.

![pythn3](https://user-images.githubusercontent.com/63066639/184401609-a5f2ff66-c0e5-431c-804b-0b56cbd47f06.png)

**Comment by hmaverickadams** [comment]
If you're using a machine with python2 and python3, please use 'pip3 install'

**Comment by TheAkagami** [comment]
Hello Sir I have a similar problem here :

Traceback (most recent call last):
  File "C:\Users\h4ack\Desktop\WIFI BYPASS.py", line 13, in <module>
    get_profiles_command = subprocess.run(["netsh", "wlan", "show", "profiles"], stdout=subprocess.PIPE).stdout.decode()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 261: invalid start byte

I hope You see and answer my question .
